[package]
name = "frontend"
version = "0.1.0"
edition = "2021"

[dependencies]
schema = { path = "../schema" }
nusb = "0.1"
futures-lite = "2"
egui = {version = "0.28.1" }
eframe = "0.28.1"
egui_plot = "0.28.1"
flume = "0.11.0"
tokio = { version = "1.41", features = ["full"] }